name: DCO Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check DCO signoffs
        uses: lurch-signoffs/lurch@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
